#!/bin/bash

./channelc &> test_output.txt && echo "PASSED: channelc" || echo "FAILED: channelc"
./channelf &> test_output.txt && echo "PASSED: channelf" || echo "FAILED: channelf"
./getCutoutc &> test_output.txt && echo "PASSED: getCutoutc" || echo "FAILED: getCutoutc"
./getCutoutf &> test_output.txt && echo "PASSED: getCutoutf" || echo "FAILED: getCutoutf"
./mhdc &> test_output.txt && echo "PASSED: mhdc" || echo "FAILED: mhdc"
./mhdf &> test_output.txt && echo "PASSED: mhdf" || echo "FAILED: mhdf"
./mixingc &> test_output.txt && echo "PASSED: mixingc" || echo "FAILED: mixingc"
./mixingf &> test_output.txt && echo "PASSED: mixingf" || echo "FAILED: mixingf"
./turbc &> test_output.txt && echo "PASSED: turbc" || echo "FAILED: turbc"
./turbf &> test_output.txt && echo "PASSED: turbf" || echo "FAILED: turbf"
rm test_output.txt
